Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -128,7 +128,6 @@ jobs:
         with:
           arch: ${{ matrix.arch }}
 
-
       - name: Get Visual Studio path
         run: |
           vswhere.exe -property installationPath
@@ -164,34 +163,155 @@ jobs:
           ls -R "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}\extras\visual_studio_integration\MSBuildExtensions"
           ls -R "${{env.VS_PATH}}\MSBuild\Microsoft\VC\v160\BuildCustomizations"
           ls -R "${{env.VS_PATH}}\MSBuild\Microsoft\VC\v170\BuildCustomizations"
-      - name: Cache cuDNN
-        id: cache-cudnn
-        uses: actions/cache@v5
+#      - name: Cache cuDNN
+#        id: cache-cudnn
+#        uses: actions/cache@v5
+#        with:
+#          path: "C:\\Program Files\\NVIDIA\\CUDNN\\v9.20"
+#          key: CUDNN_V9_20
+#      - name: Download cuDNN
+#        if: steps.cache-cudnn.outputs.cache-hit != 'true'
+#        run: |
+#          curl --ssl-revoke-best-effort -L "https://developer.download.nvidia.com/compute/cudnn/9.20.0/local_installers/cudnn_9.20.0_windows_x86_64.exe" -o "cuDNN.exe"
+#      - name: Install cuDNN
+#        if: steps.cache-cudnn.outputs.cache-hit != 'true'
+#        run: |
+#          Start-Process -Wait "cuDNN.exe" -ArgumentList "-s"
+#      - name: Set cuDNN path
+#        run: |
+#          echo "CUDNN_PATH=C:\Program Files\NVIDIA\CUDNN\v9.20" >> $env:GITHUB_ENV
+#          echo "CUDNN_HOME=C:\Program Files\NVIDIA\CUDNN\v9.20" >> $env:GITHUB_ENV
+#          Add-Content -Path $env:GITHUB_PATH -Value "C:\Program Files\NVIDIA\CUDNN\v9.20\bin\${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}\x64"
+#          echo "PATH=$Env:Path" >> $env:GITHUB_ENV
+#      - name: Download TensorRT
+#        run: |
+#          curl --ssl-revoke-best-effort --create-dirs -L "https://developer.download.nvidia.com/compute/machine-learning/tensorrt/${{env.TENSORRT_VERSION_MAJOR}}.${{env.TENSORRT_VERSION_MINOR}}.${{env.TENSORRT_VERSION_PATCH}}/zip/TensorRT-${{env.TENSORRT_VERSION_MAJOR}}.${{env.TENSORRT_VERSION_MINOR}}.${{env.TENSORRT_VERSION_PATCH}}.${{env.TENSORRT_VERSION_BUILD}}.Windows.amd64.cuda-${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}.zip" -o "TensorRT.zip" || true
+#          7z x "TensorRT.zip"
+#          Add-Content -Path $env:GITHUB_PATH -Value "${{github.workspace}}\TensorRT-${{env.TENSORRT_VERSION_MAJOR}}.${{env.TENSORRT_VERSION_MINOR}}.${{env.TENSORRT_VERSION_PATCH}}.${{env.TENSORRT_VERSION_BUILD}}\bin"
+#      - name: Download TensorRT RTX
+#        run: |
+#          curl --ssl-revoke-best-effort --fail --create-dirs -L "https://developer.nvidia.com/downloads/trt/rtx_sdk/secure/${{env.TENSORRT_RTX_VERSION_MAJOR}}.${{env.TENSORRT_RTX_VERSION_MINOR}}/TensorRT-RTX-${{env.TENSORRT_RTX_VERSION_MAJOR}}.${{env.TENSORRT_RTX_VERSION_MINOR}}.${{env.TENSORRT_RTX_VERSION_PATCH}}.${{env.TENSORRT_RTX_VERSION_BUILD}}.Windows.win10.cuda-${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}.zip" -o "TensorRT-RTX.zip" || true
+#          curl --ssl-revoke-best-effort --fail --create-dirs -L "https://developer.nvidia.com/downloads/trt/rtx_sdk/secure/${{env.TENSORRT_RTX_VERSION_MAJOR}}.${{env.TENSORRT_RTX_VERSION_MINOR}}/TensorRT-RTX-${{env.TENSORRT_RTX_VERSION_MAJOR}}.${{env.TENSORRT_RTX_VERSION_MINOR}}.${{env.TENSORRT_RTX_VERSION_PATCH}}.${{env.TENSORRT_RTX_VERSION_BUILD}}-Windows-amd64-cuda-${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}-Release-external.zip" -o "TensorRT-RTX.zip" || true
+#          7z x "TensorRT-RTX.zip"
+#          Add-Content -Path $env:GITHUB_PATH -Value "${{github.workspace}}\TensorRT-RTX-${{env.TENSORRT_RTX_VERSION_MAJOR}}.${{env.TENSORRT_RTX_VERSION_MINOR}}.${{env.TENSORRT_RTX_VERSION_PATCH}}.${{env.TENSORRT_RTX_VERSION_BUILD}}\lib"
+
+      - name: Download onnxruntime
+        run: |
+          curl --ssl-revoke-best-effort --create-dirs -L "https://github.com/ThreeDeeJay/onnxruntime/releases/download/TensorRT-RTX-75/onnxruntime.zip" -o "onnxruntime.zip"
+          git clone https://github.com/ThreeDeeJay/onnxruntime --branch multi-ep --depth 1
+          7z x "onnxruntime.zip"
+          move "Win64" "onnxruntime\lib"
+
+      - name: Configure CMake
+        run: >
+          cmake -B build
+          -A ${{ matrix.cmake_arch }}
+          -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake
+          -DVCPKG_TARGET_TRIPLET=${{ matrix.vcpkg_triplet }}
+          "-DVCPKG_INSTALLED_DIR=${{ github.workspace }}\vcpkg_installed"
+          -DCMAKE_BUILD_TYPE=Release
+          -DORT_BACKEND=${{ matrix.ort_backend }}
+          -DORT_UNIFIED_DIR="${{github.workspace}}\onnxruntime"
+        shell: cmd
+
+"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9\include\cuda_runtime.h"
+
+
+      - name: Build
+        run: cmake --build build --config Release --parallel
+        shell: cmd
+
+      # Upload the entire output directory (includes all runtime DLLs).
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
         with:
-          path: "C:\\Program Files\\NVIDIA\\CUDNN\\v9.20"
-          key: CUDNN_V9_20
-      - name: Download cuDNN
-        if: steps.cache-cudnn.outputs.cache-hit != 'true'
+          name: ${{ matrix.artifact_name }}
+          path: build/${{ matrix.ax_dir }}/
+          if-no-files-found: error
+
+  Release:
+    name: Release
+    runs-on: windows-latest
+    needs: build
+    steps:
+
+      - name: Clone repo and submodules
+        run: git clone https://${{github.repository_owner}}:${{github.token}}@github.com/${{github.repository}}.git "${{github.workspace}}" --branch ${{env.Branch}} --recurse-submodules
+
+      - name: Get current date, commit hash and count
         run: |
-          curl --ssl-revoke-best-effort -L "https://developer.download.nvidia.com/compute/cudnn/9.20.0/local_installers/cudnn_9.20.0_windows_x86_64.exe" -o "cuDNN.exe"
-      - name: Install cuDNN
-        if: steps.cache-cudnn.outputs.cache-hit != 'true'
+          echo "FirstCommitHash=$(git rev-list --max-parents=0 HEAD --first-parent)" >> $env:GITHUB_ENV
+          echo "CommitHash=$(git rev-parse HEAD)" >> $env:GITHUB_ENV
+          echo "CommitHashShort=$(git rev-parse --short=7 HEAD)" >> $env:GITHUB_ENV
+          echo "CommitCount=$(git rev-list --count HEAD)" >> $env:GITHUB_ENV
+          echo "CommitDate=$(git show -s --date=format:'%Y-%m-%d' --format=%cd)" >> $env:GITHUB_ENV
+
+#      - name: Download x86 DirectML
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: 3Deflatten_x86_DirectML
+#          path: Release\Win32
+
+#      - name: Download x64 DirectML
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: 3Deflatten_x64_DirectML
+#          path: Release\Win64
+#
+#      - name: Download x64 GPU (TensorRT+CUDA)
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: 3Deflatten_x64_GPU
+#          path: Release\Win64_GPU
+
+      - name: Download x64 Unified
+        uses: actions/download-artifact@v4
+        with:
+          name: 3Deflatten_x64_Unified
+          path: Release\Win64_Unified
+
+      - name: Deploy
         run: |
-          Start-Process -Wait "cuDNN.exe" -ArgumentList "-s"
-      - name: Set cuDNN path
+          copy "3Deflatten.ini"                          "Release/Win64_Unified/"
+          copy "README.md"                               "Release/ReadMe.txt"
+          copy "LICENSE"                                 "Release/License.txt"
+          copy "scripts/register.bat"                    "Release/"
+          copy "scripts/unregister.bat"                  "Release/"
+          copy "scripts/Setup.py"                        "Release/"
+          copy "scripts/collect_runtime_dlls.py"         "Release/"
+          copy "scripts/collect_runtime_dlls_cuda12.py"  "Release/"
+          copy "scripts/collect_runtime_dlls_cuda13.py"  "Release/"
+#copy "3Deflatten.ini"                          "Release/Win64/"
+#copy "3Deflatten.ini"                          "Release/Win64_GPU/"
+#copy "3Deflatten.ini"                   "Release/Win32/"
+#copy -r "Artifacts/Win64"               "Release"
+#copy -r "Artifacts/Win64_GPU"           "Release"
+#copy -r "Artifacts/Win32"               "Release"
+
+  
+      - name: Compress artifacts
+        if: github.event_name == 'push'
         run: |
-          echo "CUDNN_PATH=C:\Program Files\NVIDIA\CUDNN\v9.20" >> $env:GITHUB_ENV
-          echo "CUDNN_HOME=C:\Program Files\NVIDIA\CUDNN\v9.20" >> $env:GITHUB_ENV
-          Add-Content -Path $env:GITHUB_PATH -Value "C:\Program Files\NVIDIA\CUDNN\v9.20\bin\${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}\x64"
-          echo "PATH=$Env:Path" >> $env:GITHUB_ENV
-      - name: Download TensorRT
+          7z a "Release/${{env.Title}}.zip" "${{github.workspace}}/Release/*" -mx=9
+          cp "Release/${{env.Title}}.zip" "Release/${{env.Title}}_r${{env.CommitCount}}@${{env.CommitHashShort}}.zip"
+  
+      - name: Purge tag - latest-${{env.Branch}}
+        if: github.event_name == 'push'
         run: |
-          curl --ssl-revoke-best-effort --create-dirs -L "https://developer.download.nvidia.com/compute/machine-learning/tensorrt/${{env.TENSORRT_VERSION_MAJOR}}.${{env.TENSORRT_VERSION_MINOR}}.${{env.TENSORRT_VERSION_PATCH}}/zip/TensorRT-${{env.TENSORRT_VERSION_MAJOR}}.${{env.TENSORRT_VERSION_MINOR}}.${{env.TENSORRT_VERSION_PATCH}}.${{env.TENSORRT_VERSION_BUILD}}.Windows.amd64.cuda-${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}.zip" -o "TensorRT.zip" || true
-          7z x "TensorRT.zip"
-          Add-Content -Path $env:GITHUB_PATH -Value "${{github.workspace}}\TensorRT-${{env.TENSORRT_VERSION_MAJOR}}.${{env.TENSORRT_VERSION_MINOR}}.${{env.TENSORRT_VERSION_PATCH}}.${{env.TENSORRT_VERSION_BUILD}}\bin"
-      - name: Download TensorRT RTX
+          gh release delete latest-${{env.Branch}} --repo ${{github.repository}} --cleanup-tag --yes || true
+  
+      - name: Release - archive-${{env.Branch}}
+        if: github.event_name == 'push'
         run: |
-          curl --ssl-revoke-best-effort --fail --create-dirs -L "https://developer.nvidia.com/downloads/trt/rtx_sdk/secure/${{env.TENSORRT_RTX_VERSION_MAJOR}}.${{env.TENSORRT_RTX_VERSION_MINOR}}/TensorRT-RTX-${{env.TENSORRT_RTX_VERSION_MAJOR}}.${{env.TENSORRT_RTX_VERSION_MINOR}}.${{env.TENSORRT_RTX_VERSION_PATCH}}.${{env.TENSORRT_RTX_VERSION_BUILD}}.Windows.win10.cuda-${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}.zip" -o "TensorRT-RTX.zip" || true
-          curl --ssl-revoke-best-effort --fail --create-dirs -L "https://developer.nvidia.com/downloads/trt/rtx_sdk/secure/${{env.TENSORRT_RTX_VERSION_MAJOR}}.${{env.TENSORRT_RTX_VERSION_MINOR}}/TensorRT-RTX-${{env.TENSORRT_RTX_VERSION_MAJOR}}.${{env.TENSORRT_RTX_VERSION_MINOR}}.${{env.TENSORRT_RTX_VERSION_PATCH}}.${{env.TENSORRT_RTX_VERSION_BUILD}}-Windows-amd64-cuda-${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}-Release-external.zip" -o "TensorRT-RTX.zip" || true
-          7z x "TensorRT-RTX.zip"
-          Add-Content -Path $env:GITHUB_PATH -Value "${{github.workspace}}\TensorRT-RTX-${{env.TENSORRT_RTX_VERSION_MAJOR}}.${{env.TENSORRT_RTX_VERSION_MINOR}}.${{env.TENSORRT_RTX_VERSION_PATCH}}.${{env.TENSORRT_RTX_VERSION_BUILD}}\lib"
+          gh release create archive-${{env.Branch}} --repo ${{github.repository}} --target ${{env.FirstCommitHash}} --latest=false --prerelease --title "${{env.Title}} ${{env.Branch}} build archive" --notes "Latest build: https://github.com/${{github.repository}}/releases/latest-${{env.Branch}}
+          Build logs: https://github.com/${{github.repository}}/actions" || true
+          gh release edit archive-${{env.Branch}} --repo ${{github.repository}} --target ${{env.FirstCommitHash}} --latest=false --prerelease --title "${{env.Title}} ${{env.Branch}} build archive" --notes "Latest build: https://github.com/${{github.repository}}/releases/latest-${{env.Branch}}
+          Build logs: https://github.com/${{github.repository}}/actions" || true
+          gh release upload archive-${{env.Branch}} --repo ${{github.repository}} --clobber "Release/${{env.Title}}_r${{env.CommitCount}}@${{env.CommitHashShort}}.zip"
+  
+      - name: Release - latest-${{env.Branch}}
+        if: github.event_name == 'push'
+        run: |
+          gh release create latest-${{env.Branch}} --repo ${{github.repository}} --target ${{env.CommitHash}} --generate-notes --latest=true --title "${{env.Title}} r${{env.CommitCount}}@${{env.CommitHashShort}}" --notes "Build archive: https://github.com/${{github.repository}}/releases/tag/archive-${{env.Branch}}
+          Build log: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
+          gh release upload latest-${{env.Branch}} --repo ${{github.repository}} --clobber "Release/${{env.Title}}.zip"
